### ISSUE TITLE
Some issues with the pre/post list in Info panel

### ISSUE THREAD

**Issue by yiyin** [FlyBrainLab/NeuroMynerva#24]
1. Neuron's `name` is displayed in info panel's pre/post synaptic partners, should be `uname`.
2. The textbox for filtering neuron names and number of synapse seems to be connected to the button for sorting the column. Once I click in the textbox, it changes sort order.
3. A button for adding/removing all listed neurons or synapses would be useful, to mirror the latest NeuroNLP webpages.
4. Use rid to add/remove neuron/synapse, rather than uname. All the servers have been updated to take rid queries. This is much faster, see hemibrain NeuroNLP webpage for comparison.
5. delete button in Neu3D window does not change +/- sign in the pre/post list.
6. Clicking on a synapse does not show anything in info panel. Should probably mirror what's in the hemibrain NeuroNLP webpage.

**Comment by TK-21st** [comment]
- [x] 1. addressed in f95b73ce6b97828c2aa1a36563c05bcf5812e2c0
- [ ] 2.
- [ ] 3.
- [ ] 4.
- [ ] 5.
- [ ] 6.

**Comment by yiyin** [comment]
7. Clicking on the trash can button in the Neu3D window to remove everything does not change '-' sign into '+' in the pre/post list.

**Comment by TK-21st** [comment]
> 7. Clicking on the trash can button in the Neu3D window to remove everything does not change '-' sign into '+' in the pre/post list.

This is a duplicate of point 5 I believe, still remains to be fixed.

**Comment by yiyin** [comment]
> > 1. Clicking on the trash can button in the Neu3D window to remove everything does not change '-' sign into '+' in the pre/post list.
> 
> This is a duplicate of point 5 I believe, still remains to be fixed.

Oh, yes. Sorry!

**Comment by TK-21st** [comment]
All fixed.

**Comment by yiyin** [comment]
When clicking on a neuron without pre/post info, pre/postsynaptic partners show "0 Neurons", but the list of neurons still showing the pre/post of the previously clicked neuron. For example, in FlyCircuit, "show $TH-F-70001$" and click on a neuron until you see the pre/post partner, then click on the neuron "TH-F-700013", you will see the list shows the pre/post neurons of the one you clicked prior to "TH-F-700013".

**Comment by yiyin** [comment]
It seems that #2 remains an issue on 0.2.7. 
For #3, would be useful if the button will add/remove only the ones that are filtered out.

**Comment by TK-21st** [comment]
@yiyin did you click on the input field itself or did you click on the rectangle around the input field? The header sorts the column if you click on the space around the input field.

**Comment by yiyin** [comment]
I click on the input field to type in something and the order of the list changed.

**Comment by TK-21st** [comment]
- Issue with 3 addressed in e89128d9cf84d24150cc2e8c9a1e9b34a6bb21af
- Issue with neuron without synaptic partners addressed in 33816057266df82be37694204e9dd4a12137ff4a

**Comment by yiyin** [comment]
Issue with 3: neurons are filtered correctly. However, when pushing the + button, it still asks if you want to add all N neurons, where N is the total number of unfiltered neurons, might be confusing.

**Comment by yiyin** [comment]
Also the +/- buttons are very slow. The neurons are added/removed from Neu3D window pretty quickly, suggesting the query from neuroarch server has finished, but the prompt is not returned back to user, kernel still showing busy. It seems to be stuck on this line https://github.com/FlyBrainLab/NeuroMynerva/blob/b9102524d49045ab24852fd265659eb9e0d11ded/src/widgets/neu3d-widget/widget.tsx#L461 for a long time before it is released and the subsequent console.log is not printed until right before the kernel is released from busy state.

**Comment by TK-21st** [comment]
> Also the +/- buttons are very slow. The neurons are added/removed from Neu3D window pretty quickly, suggesting the query from neuroarch server has finished, but the prompt is not returned back to user, kernel still showing busy. It seems to be stuck on this line
> 
> https://github.com/FlyBrainLab/NeuroMynerva/blob/b9102524d49045ab24852fd265659eb9e0d11ded/src/widgets/neu3d-widget/widget.tsx#L461
> 
> for a long time before it is released and the subsequent console.log is not printed until right before the kernel is released from busy state.

Yes, the kernel call is the bottleneck. Just pushed 2743ffa that attempts to solve this issue.

**Comment by TK-21st** [comment]
> Issue with 3: neurons are filtered correctly. However, when pushing the + button, it still asks if you want to add all N neurons, where N is the total number of unfiltered neurons, might be confusing.

Note sure I understand. In the image below, the `to be added` should reflect the number of neurons that are currently in the table and are not already in the workspace. 

![image](https://user-images.githubusercontent.com/26802334/103287621-f3e6e800-49b0-11eb-9b26-21aa9c8944ce.png)

**Comment by yiyin** [comment]
I think the problem is Total, I feel that for me it is more intuitive to have this number to be the number in the filtered list.

**Comment by TK-21st** [comment]
@yiyin 

How about showing a table in the pop-up like this:

| Type | Number|
|:------|:--------:|
|Total Presynaptic Partners| 68|
|Active in Connectivity Table | 27 |
|Currently in Workspace | 1 |
|To be Added | 26 |

**Comment by yiyin** [comment]
sounds good

**Comment by TK-21st** [comment]
addressed in 0e5ce6851402591cb97ff1f3cd7b0c267577bd6f
